//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myhtml.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public string Date { get; set; }
        public string ContactOne { get; set; }
        public string ContactTwo { get; set; }
        public string ContactThree { get; set; }
        public string ContactFour { get; set; }
        public string ContactFive { get; set; }
        public string ContactSix { get; set; }
        public string ContactSeven { get; set; }
        public string ContactEight { get; set; }
        public string SeeDate { get; set; }
    }
}
